basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is a sample server for demonstrating Swagger with Fiber
  title: Fiber Swagger Example API
  version: "1.0"
paths: {}
swagger: "2.0"
